repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: trufflehog git file://. --since-commit HEAD --no-verification --fail
        #entry: wsl.exe sh -c "echo $(which trufflehog) git file://. --since-commit HEAD --no-verification --fail"
       #  entry: docker run --rm -it -v "$PWD:/pwd" trufflesecurity/trufflehog:latest git file://. --since-commit HEAD --no-verification --fail
        # e#ntry: docker run --rm -t -v "$PWD:/pwd" trufflesecurity/trufflehog:latest git file:///pwd --since-commit HEAD --no-verification --fail
        # entry: bash -c '$(command -v trufflehog || echo $(find_trufflehog)) "$@"' git file://. --since-commit HEAD --no-verification --fail
        language: system
        stages: ["pre-commit", "pre-push"]
