apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: radix-acr-cleanup
  title: Radix ACR cleanup
  description: "Cleanup service for images no longer used in the cluster"
  annotations:
    github.com/project-slug: equinor/radix-acr-cleanup
spec:
  type: service
  lifecycle: production
  owner: team-radix
  system: system:default/Radix
