registry: radixdev
clusterType: development
deleteUntagged: false
servicePrincipalSecret: radix-sp-acr-azure

replicaCount: 1

image:
  repository: xx
  tag: xx
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: 
  limits:
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi

nodeSelector: {}

tolerations: []

affinity: {}
