registry: xx
clusterType: xx
deleteUntagged: false
performDelete: false
servicePrincipalSecret: radix-sp-acr-azure
period: 60m

metrics:
  enabled: false

replicaCount: 1

image:
  repository: xx
  tag: xx
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: 
  limits:
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi

nodeSelector: {}

tolerations: []

affinity: {}
