apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radix-acr-cleanup.fullname" . }}
  labels:
    {{- include "radix-acr-cleanup.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "radix-acr-cleanup.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if (.Values.metrics.enabled) }}
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        {{- if (.Values.metrics.annotations) }}
        {{- toYaml .Values.metrics.annotations | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "radix-acr-cleanup.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "radix-acr-cleanup.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: AZURE_TENANT_ID
              value: {{ .Values.azureTenantId }}
            - name: AZURE_CREDENTIALS_FILE
              value: {{ .Values.azureCredentialsFile }}
            - name: PERIOD
              value: {{ .Values.period }}
            - name: REGISTRY
              value: {{ .Values.registry }}
            - name: CLUSTER_TYPE
              value: {{ .Values.clusterType }}
            - name: ACTIVE_CLUSTER_NAME
              value: {{ .Values.activeClusterName }}
            - name: DELETE_UNTAGGED
              value: {{ .Values.deleteUntagged | quote }}
            - name: RETAIN_LATEST_UNTAGGED
              value: {{ .Values.retainLatestUntagged | quote }}
            - name: PERFORM_DELETE
              value: {{ .Values.performDelete | quote }}
            - name: CLEANUP_DAYS
              value: {{ .Values.cleanupDays | quote }}
            - name: CLEANUP_START
              value: {{ .Values.cleanupStart | quote }}
            - name: CLEANUP_END
              value: {{ .Values.cleanupEnd | quote }}
            - name: WHITELISTED
              value: {{ include "helm-toolkit.utils.joinListWithComma" .Values.whitelisted | quote }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: {{ .Values.servicePrincipalSecret }}
              mountPath: /app/.azure
              readOnly: true
            {{- with .Values.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Values.servicePrincipalSecret }}
          secret:
            secretName: {{ .Values.servicePrincipalSecret }}
        {{- with .Values.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
