apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "radix-acr-cleanup.fullname" . }}
  labels:
    {{- include "radix-acr-cleanup.labels" . | nindent 4 }}
rules:
- apiGroups:
  - radix.equinor.com
  resources:
  - radixdeployments
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "radix-acr-cleanup.fullname" . }}
  labels:
    {{- include "radix-acr-cleanup.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "radix-acr-cleanup.fullname" . }}
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "radix-acr-cleanup.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "radix-acr-cleanup-rbac.radixconfig-role" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "radix-acr-cleanup.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  resourceNames:
  - radix-config
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "radix-acr-cleanup-rbac.radixconfig-role" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "radix-acr-cleanup.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "radix-acr-cleanup-rbac.radixconfig-role" . }}"
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "radix-acr-cleanup.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}