apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "radix-acr-cleanup.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "radix-acr-cleanup.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}    