apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Chart.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ include "radix-acr-cleanup.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"