name: radix-acr-cleanup-build
on:
  push:
    branches:
      - master
      - release
permissions:
  id-token: write
jobs:
  build-deploy-image-dev:
    name: Build-push to dev
    env:
      IMAGE: radix-acr-cleanup
      CONTAINER_REGISTRIES: radixdev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
      - name: 'Build docker image'
        run: |
          for registry in `echo ${{ env.CONTAINER_REGISTRIES }} | tr ',' '\n'`
          do
            docker build . -t ${registry}.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
          done
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      - name: 'Push to dev'
        run: |
          for registry in `echo ${{ env.CONTAINER_REGISTRIES }} | tr ',' '\n'`
          do
            az acr login --name ${registry}
            docker push ${registry}.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
          done
  build-deploy-image-prod:
    if: github.ref == 'refs/heads/release'
    name: Build-push to prod
    env:
      IMAGE: radix-acr-cleanup
      CONTAINER_REGISTRIES: radixprod,radixc2prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
      - name: 'Build docker image'
        run: |
          for registry in `echo ${{ env.CONTAINER_REGISTRIES }} | tr ',' '\n'`
          do
            docker build . -t ${registry}.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }} 
          done
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_PROD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }}
      - name: 'Push to prod'
        run: |
          for registry in `echo ${{ env.CONTAINER_REGISTRIES }} | tr ',' '\n'`
          do
            az acr login --name ${registry}
            docker push ${registry}.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
          done
