name: radix-acr-cleanup-build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          docker build . -t radixdev.azurecr.io/radix-acr-cleanup:${GITHUB_REF##*/}-${{ github.sha }} -t radixprod.azurecr.io/radix-acr-cleanup:${GITHUB_REF##*/}-${{ github.sha }} -t radixus.azurecr.io/radix-acr-cleanup:${GITHUB_REF##*/}-${{ github.sha }}
      - uses: azure/docker-login@v1
        with:
          login-server: radixdev.azurecr.io
          username: ${{ secrets.DEV_REGISTRY_USERNAME }}
          password: ${{ secrets.DEV_REGISTRY_PASSWORD }}
      - name: push to radixdev
        run: |
          docker push radixdev.azurecr.io/radix-acr-cleanup:${GITHUB_REF##*/}-${{ github.sha }}
      - uses: azure/docker-login@v1
        with:
          login-server: radixprod.azurecr.io
          username: ${{ secrets.PROD_REGISTRY_USERNAME }}
          password: ${{ secrets.PROD_REGISTRY_PASSWORD }}
      - name: push to radixprod
        run: |
          docker push radixprod.azurecr.io/radix-acr-cleanup:${GITHUB_REF##*/}-${{ github.sha }}
      - uses: azure/docker-login@v1
        with:
          login-server: radixus.azurecr.io
          username: ${{ secrets.PROD_REGISTRY_USERNAME }}
          password: ${{ secrets.PROD_REGISTRY_PASSWORD }}
      - name: push to radixus
        run: |
          docker push radixus.azurecr.io/radix-acr-cleanup:${GITHUB_REF##*/}-${{ github.sha }}
