name: radix-acr-cleanup-pr
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    name: pull-request-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      env:
        REF: ${{ github. sha }}
      run: docker build -t radix-acr-cleanup:${REF##*/} .
