# Pipeline to release radix-acr-cleanup. Will be released to Dev and Prod subscription
# for both master and release. Flux will use master image in Dev while will use release
# image in prod

trigger:
- master
- release

# no PR builds
pr: none

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  serviceConnectionDockerregistryDev: 'radix-azure-devops-dev-cr'
  serviceConnectionDockerregistryProd: 'radix-azure-devops-prod-cr'
  serviceConnectionDockerregistryUs: 'radix-azure-devops-us-cr'

steps:
- task: Docker@2
  displayName: 'Login to Dev ACR'
  inputs:
    command: login
    containerRegistry: '$(serviceConnectionDockerregistryDev)'
- task: Docker@2
  displayName: 'Login to Prod ACR'
  inputs:
    command: login
    containerRegistry: '$(serviceConnectionDockerregistryProd)'
- task: Docker@2
  displayName: 'Login to US ACR'
  inputs:
    command: login
    containerRegistry: '$(serviceConnectionDockerregistryUs)'

- task: Docker@2
  displayName: 'Build and push image'
  inputs:
    command: buildAndPush
    dockerFile: 'Dockerfile'
    repository: 'radix-acr-cleanup'
    tags: |
      $(build.SourceBranchName)-$(Build.SourceVersion)