# Pipeline to release radix-acr-cleanup. Will be released to Dev and Prod subscription
# for both master and release. Flux will use master image in Dev while will use release
# image in prod

trigger:
- master
- release

# no PR builds
pr: none

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  serviceConnectionDevSubscription: 'radix-azure-devops-dev-cr'

steps:
- task: Docker@2
  displayName: 'Login to Dev Subscription'
  inputs:
    command: login
    containerRegistry: '$(serviceConnectionDevSubscription)'

- task: Docker@2
  displayName: 'Build and push image'
  inputs:
    command: buildAndPush
    dockerFile: 'Dockerfile'
    repository: 'radix-acr-cleanup'
    tags: |
      $(build.SourceBranchName)-$(Build.SourceVersion)